"""initial

Revision ID: 4cc588f5d460
Revises: 
Create Date: 2026-08-05 12:30:38.658425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cc588f5d460'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ag_abfrage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('building',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('entity_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=False),
    sa.Column('change_source', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_history_entity_id'), 'entity_history', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_history_entity_type'), 'entity_history', ['entity_type'], unique=False)
    op.create_index('ix_entity_history_type_id', 'entity_history', ['entity_type', 'entity_id'], unique=False)
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('intranet_username', sa.String(), nullable=False),
    sa.Column('intranet_uuid', sa.Uuid(), nullable=False),
    sa.Column('is_flinta', sa.Boolean(), nullable=False),
    sa.Column('study_subject', sa.String(), nullable=True),
    sa.Column('apprenticeship_field', sa.String(), nullable=True),
    sa.Column('barrier_free_needed', sa.Boolean(), nullable=False),
    sa.Column('mailbox_key', sa.Boolean(), nullable=False),
    sa.Column('mailbox_list_opt_in', sa.Boolean(), nullable=False),
    sa.Column('soli_miete_wunsch', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_sublet', sa.Boolean(), nullable=False),
    sa.Column('sublet_from', sa.Date(), nullable=True),
    sa.Column('sublet_to', sa.Date(), nullable=True),
    sa.Column('sublet_of_tenant_id', sa.Integer(), nullable=True),
    sa.Column('move_in', sa.Date(), nullable=False),
    sa.Column('move_out', sa.Date(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sublet_of_tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intranet_username'),
    sa.UniqueConstraint('intranet_uuid')
    )
    op.create_table('ag_abfrage_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('abfrage_id', sa.Integer(), nullable=False),
    sa.Column('ag_name', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'NOT_ACTIVE_ENOUGH', 'CONTACTED', 'INACTIVE', name='agstatus'), nullable=False),
    sa.ForeignKeyConstraint(['abfrage_id'], ['ag_abfrage.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollment_proof',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_type', sa.Enum('STUDY', 'APPRENTICESHIP', name='enrollmenttype'), nullable=False),
    sa.Column('enrollment_name', sa.String(), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wg',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wg_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('size_sqm', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('has_mattress', sa.Boolean(), nullable=False),
    sa.Column('has_bed', sa.Boolean(), nullable=False),
    sa.Column('has_table', sa.Boolean(), nullable=False),
    sa.Column('has_closet', sa.Boolean(), nullable=False),
    sa.Column('freifinanziert', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['wg_id'], ['wg.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_room_assignment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('moved_in', sa.Date(), nullable=False),
    sa.Column('moved_out', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_room_assignment')
    op.drop_table('room')
    op.drop_table('wg')
    op.drop_table('enrollment_proof')
    op.drop_table('ag_abfrage_result')
    op.drop_table('tenant')
    op.drop_index('ix_entity_history_type_id', table_name='entity_history')
    op.drop_index(op.f('ix_entity_history_entity_type'), table_name='entity_history')
    op.drop_index(op.f('ix_entity_history_entity_id'), table_name='entity_history')
    op.drop_table('entity_history')
    op.drop_table('building')
    op.drop_table('ag_abfrage')
    # ### end Alembic commands ###
