"""uebergabe

Revision ID: 5e6297a8ef91
Revises: a7e3c1f09b42
Create Date: 2026-10-07 02:34:47.036479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from cartei_db.base import create_audit_trigger_sql, drop_audit_trigger_sql


# revision identifiers, used by Alembic.
revision: str = '5e6297a8ef91'
down_revision: Union[str, Sequence[str], None] = 'a7e3c1f09b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uebergabe',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('tenant_room_assignment_id', sa.Integer(), nullable=True),
    sa.Column('conducted_by_id', sa.Integer(), nullable=False),
    sa.Column('conducted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['conducted_by_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['tenant_room_assignment_id'], ['tenant_room_assignment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(create_audit_trigger_sql('uebergabe', set()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(drop_audit_trigger_sql('uebergabe'))
    op.drop_table('uebergabe')
    # ### end Alembic commands ###
