"""move mailbox_key and sublet to room assignment, split key handover into received/returned dates

Revision ID: d69d4eb566ce
Revises: 8381111cd9de
Create Date: 2026-08-16 14:38:41.389599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd69d4eb566ce'
down_revision: Union[str, Sequence[str], None] = '8381111cd9de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tenant_sublet_of_tenant_id_fkey'), 'tenant', type_='foreignkey')
    op.drop_column('tenant', 'mailbox_key')
    op.drop_column('tenant', 'sublet_to')
    op.drop_column('tenant', 'sublet_of_tenant_id')
    op.drop_column('tenant', 'sublet_from')
    op.drop_column('tenant', 'is_sublet')
    op.add_column('tenant_room_assignment', sa.Column('mailbox_key', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('tenant_room_assignment', sa.Column('is_sublet', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('tenant_room_assignment', sa.Column('sublet_of_tenant_id', sa.Integer(), nullable=True))
    op.add_column('tenant_room_assignment', sa.Column('key_received', sa.Date(), nullable=True))
    op.add_column('tenant_room_assignment', sa.Column('key_returned', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'tenant_room_assignment', 'tenant', ['sublet_of_tenant_id'], ['id'])
    op.drop_column('tenant_room_assignment', 'key_handed_over')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_room_assignment', sa.Column('key_handed_over', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tenant_room_assignment', type_='foreignkey')
    op.drop_column('tenant_room_assignment', 'key_returned')
    op.drop_column('tenant_room_assignment', 'key_received')
    op.drop_column('tenant_room_assignment', 'sublet_of_tenant_id')
    op.drop_column('tenant_room_assignment', 'is_sublet')
    op.drop_column('tenant_room_assignment', 'mailbox_key')
    op.add_column('tenant', sa.Column('is_sublet', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('tenant', sa.Column('sublet_from', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('tenant', sa.Column('sublet_of_tenant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tenant', sa.Column('sublet_to', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('tenant', sa.Column('mailbox_key', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('tenant_sublet_of_tenant_id_fkey'), 'tenant', 'tenant', ['sublet_of_tenant_id'], ['id'])
    # ### end Alembic commands ###
