"""room wg damages

Revision ID: f69c41ec7771
Revises: c5d6e7f8a9b0
Create Date: 2026-08-23 23:22:57.557935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from cartei_db.damage_triggers import damage_no_delete_sql, drop_damage_no_delete_sql


# revision identifiers, used by Alembic.
revision: str = 'f69c41ec7771'
down_revision: Union[str, Sequence[str], None] = 'c5d6e7f8a9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_damage',
    sa.Column('wg_id', sa.Integer(), nullable=False),
    sa.Column('line', sa.Enum('BAD_FLECK', 'BAD_LOCH', 'BAD_KLEBER', 'BAD_SONSTIGES', 'KUECHE_FLECK', 'KUECHE_LOCH', 'KUECHE_KLEBER', 'KUECHE_SONSTIGES', 'GEMEINSCHAFT_FLECK', 'GEMEINSCHAFT_LOCH', 'GEMEINSCHAFT_KLEBER', 'GEMEINSCHAFT_SONSTIGES', name='wgdamageline'), nullable=False),
    sa.Column('size', sa.Enum('LT1', 'MID', 'GT', name='damagesize'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('fixed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fixed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['fixed_by_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['wg_id'], ['wg.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_damage',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('line', sa.Enum('BODEN_FLECKEN', 'BODEN_LOECHER', 'FUSSLEISTE_FLECKEN', 'WAND_FLECKEN', 'WAND_LOECHER', 'WAND_KLEBER', 'TUER_FLECKEN', 'TUER_LOECHER', 'FENSTER_RAHMEN_FLECKEN', 'FENSTER_BANK_FLECKEN', 'FENSTER_KLEBER', 'BETT_FLECKEN', 'BETT_LOECHER', 'MATRATZE_FLECKEN', 'SCHREIBTISCH_FLECKEN', 'SCHREIBTISCH_LOECHER', 'SCHRANK_FLECKEN', 'SCHRANK_LOECHER', name='roomdamageline'), nullable=False),
    sa.Column('size', sa.Enum('LT1', 'MID', 'GT', name='damagesize'), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('fixed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fixed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['fixed_by_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    for stmt in damage_no_delete_sql():
        op.execute(stmt)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for stmt in drop_damage_no_delete_sql():
        op.execute(stmt)
    op.drop_table('room_damage')
    op.drop_table('wg_damage')
    sa.Enum(name='roomdamageline').drop(op.get_bind())
    sa.Enum(name='wgdamageline').drop(op.get_bind())
    sa.Enum(name='damagesize').drop(op.get_bind())
    # ### end Alembic commands ###
